### ISSUE TITLE
Could you provide me the pretrained models for finutune?

### ISSUE THREAD

**Issue by whmin** [qijiezhao/pseudo-3d-pytorch#10]
Hi, I saw your pretrained models last time,but you cancel the links for some important reasons. If you are pleasant ,could you send me your pretrained  models ? I will not spread the source or use for business without your perssion.my email is 946044938@qq.com.Thank you very much!!!

**Comment by qijiezhao** [comment]
Sorry ,whmin,  I can only give you suggestions for transferring caffemodels to pytorchmodels :https://github.com/marvis/pytorch-caffe-darknet-convert.
