### ISSUE TITLE
Subtracting mean value before inputting video in the wild?

### ISSUE THREAD

**Issue by zhanghaoinf** [qijiezhao/pseudo-3d-pytorch#12]
Hi, @qijiezhao , I am reading and running this repo. I find mean value is defined "self.input_mean=...", but not used. so when use my own video data, is it better to subtract the mean value before inputting into p3d?
By the way, is the input channels of image are RGB instead of BGR？

**Comment by qijiezhao** [comment]
It's of course better to subtract mean values before inputting.
RGB.
