### ISSUE TITLE
Pre-trained model files are broken?

### ISSUE THREAD

**Issue by kazuyokojima** [qijiezhao/pseudo-3d-pytorch#13]
Hi, @qijiezhao .
I really appreciate your work!

I tried to use your pre-trained model (https://pan.baidu.com/s/1o8VFtMy#list/path=%2F).
However, these tar files cannot be extracted with following error message.

```
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

Could you check and give me valid tar files?

Thanks,

**Comment by karimhasebou** [comment]
Hi @kazuyokojima , I recently ran into the same issue. Then I noticed that he actually loads the files directly in pytorch. Therefore, its not really a tar.

**Comment by kazuyokojima** [comment]
@karimhasebou Thank you for your information!

**Comment by BKHMSI** [comment]
@kazuyokojima were you able to obtain the correct results using the RGB pre-trained model: `p3d_rgb_199.checkpoint.pth.tar`? You can refer to my [issue](https://github.com/qijiezhao/pseudo-3d-pytorch/issues/14) for more details
